// Decompiled with JetBrains decompiler
// Type: Microsoft.Iris.Markup.UIXLoadResultExports
// Assembly: UIX, Version=4.8.0.0, Culture=neutral, PublicKeyToken=ddd0da4d3e678217
// MVID: A56C6C9D-B7F6-46A9-8BDE-B3D9B8D60B11
// Assembly location: C:\Program Files\Zune\UIX.dll

using Microsoft.Iris.Accessibility;
using Microsoft.Iris.Animations;
using Microsoft.Iris.Debug;
using Microsoft.Iris.Drawing;
using Microsoft.Iris.Input;
using Microsoft.Iris.InputHandlers;
using Microsoft.Iris.Layout;
using Microsoft.Iris.Layouts;
using Microsoft.Iris.Markup.UIX;
using Microsoft.Iris.ModelItems;
using Microsoft.Iris.Navigation;
using Microsoft.Iris.Render;
using Microsoft.Iris.RenderAPI.Audio;
using Microsoft.Iris.UI;
using Microsoft.Iris.ViewItems;

namespace Microsoft.Iris.Markup
{
    internal static class UIXLoadResultExports
    {
        public static TypeSchema AccessibleRoleType;
        public static TypeSchema AlignmentType;
        public static TypeSchema AlphaOperationType;
        public static TypeSchema AnimationEventTypeType;
        public static TypeSchema BeginDragPolicyType;
        public static TypeSchema ClickCountType;
        public static TypeSchema ClickTypeType;
        public static TypeSchema ColorOperationType;
        public static TypeSchema ColorSchemeType;
        public static TypeSchema ContentPositioningPolicyType;
        public static TypeSchema CursorType;
        public static TypeSchema DataQueryStatusType;
        public static TypeSchema DebugLabelFormatType;
        public static TypeSchema DebugOutlineScopeType;
        public static TypeSchema DropActionType;
        public static TypeSchema EmbossDirectionType;
        public static TypeSchema FlipDirectionType;
        public static TypeSchema FocusChangeReasonType;
        public static TypeSchema FontStylesType;
        public static TypeSchema GaussianBlurModeType;
        public static TypeSchema GraphicsDeviceTypeType;
        public static TypeSchema HostStatusType;
        public static TypeSchema ImageStatusType;
        public static TypeSchema InputHandlerModifiersType;
        public static TypeSchema InputHandlerStageType;
        public static TypeSchema InputHandlerTransitionType;
        public static TypeSchema InterestPointType;
        public static TypeSchema InterpolationTypeType;
        public static TypeSchema InvokePriorityType;
        public static TypeSchema KeyHandlerKeyType;
        public static TypeSchema KeyframeFilterType;
        public static TypeSchema LineAlignmentType;
        public static TypeSchema MaximizeModeType;
        public static TypeSchema MissingItemPolicyType;
        public static TypeSchema MouseTargetType;
        public static TypeSchema NavigationPoliciesType;
        public static TypeSchema OrientationType;
        public static TypeSchema RelativeEdgeType;
        public static TypeSchema RepeatPolicyType;
        public static TypeSchema SharedSizePolicyType;
        public static TypeSchema ShortcutHandlerCommandType;
        public static TypeSchema SizingPolicyType;
        public static TypeSchema SnapshotPolicyType;
        public static TypeSchema StackPriorityType;
        public static TypeSchema StretchingPolicyType;
        public static TypeSchema StripAlignmentType;
        public static TypeSchema SystemSoundEventType;
        public static TypeSchema TextBoundsType;
        public static TypeSchema TextSharpnessType;
        public static TypeSchema TransformAttributeType;
        public static TypeSchema WindowStateType;
        public static TypeSchema[] ExportTable;

        public static void InitializeStatics()
        {
            ExportTable = new TypeSchema[243];
            AccessibleRoleType = new UIXEnumSchema(1, "AccessibleRole", typeof(AccRole), false);
            AlignmentType = new UIXEnumSchema(3, "Alignment", typeof(Alignment), false);
            AlphaOperationType = new UIXEnumSchema(5, "AlphaOperation", typeof(AlphaOperation), false);
            AnimationEventTypeType = new UIXEnumSchema(10, "AnimationEventType", typeof(AnimationEventType), false);
            BeginDragPolicyType = new UIXEnumSchema(12, "BeginDragPolicy", typeof(BeginDragPolicy), false);
            ClickCountType = new UIXEnumSchema(31, "ClickCount", typeof(ClickCount), false);
            ClickTypeType = new UIXEnumSchema(33, "ClickType", typeof(ClickType), true);
            ColorOperationType = new UIXEnumSchema(38, "ColorOperation", typeof(ColorOperation), false);
            ColorSchemeType = new UIXEnumSchema(39, "ColorScheme", typeof(ColorScheme), false);
            ContentPositioningPolicyType = new UIXEnumSchema(41, "ContentPositioningPolicy", typeof(ContentPositioningPolicy), false);
            CursorType = new UIXEnumSchema(44, "Cursor", typeof(CursorID), false);
            DataQueryStatusType = new UIXEnumSchema(47, "DataQueryStatus", typeof(DataProviderQueryStatus), false);
            DebugLabelFormatType = new UIXEnumSchema(50, "DebugLabelFormat", typeof(DebugLabelFormat), false);
            DebugOutlineScopeType = new UIXEnumSchema(51, "DebugOutlineScope", typeof(DebugOutlineScope), false);
            DropActionType = new UIXEnumSchema(64, "DropAction", typeof(DropAction), true);
            EmbossDirectionType = new UIXEnumSchema(84, "EmbossDirection", typeof(EmbossDirection), false);
            FlipDirectionType = new UIXEnumSchema(89, "FlipDirection", typeof(FlipDirection), true);
            FocusChangeReasonType = new UIXEnumSchema(91, "FocusChangeReason", typeof(FocusChangeReason), true);
            FontStylesType = new UIXEnumSchema(94, "FontStyles", typeof(FontStyles), true);
            GaussianBlurModeType = new UIXEnumSchema(96, "GaussianBlurMode", typeof(GaussianBlurMode), false);
            GraphicsDeviceTypeType = new UIXEnumSchema(98, "GraphicsDeviceType", typeof(RenderingType), false);
            HostStatusType = new UIXEnumSchema(102, "HostStatus", typeof(HostStatus), false);
            ImageStatusType = new UIXEnumSchema(108, "ImageStatus", typeof(ImageStatus), false);
            InputHandlerModifiersType = new UIXEnumSchema(111, "InputHandlerModifiers", typeof(InputHandlerModifiers), true);
            InputHandlerStageType = new UIXEnumSchema(112, "InputHandlerStage", typeof(InputHandlerStage), true);
            InputHandlerTransitionType = new UIXEnumSchema(113, "InputHandlerTransition", typeof(InputHandlerTransition), false);
            InterestPointType = new UIXEnumSchema(118, "InterestPoint", typeof(InterestPoint), false);
            InterpolationTypeType = new UIXEnumSchema(122, "InterpolationType", typeof(InterpolationType), false);
            InvokePriorityType = new UIXEnumSchema(126, "InvokePriority", typeof(InvokePriority), false);
            KeyHandlerKeyType = new UIXEnumSchema(129, "KeyHandlerKey", typeof(KeyHandlerKey), false);
            KeyframeFilterType = new UIXEnumSchema(131, "KeyframeFilter", typeof(KeyframeFilter), false);
            LineAlignmentType = new UIXEnumSchema(137, "LineAlignment", typeof(LineAlignment), false);
            MaximizeModeType = new UIXEnumSchema(146, "MaximizeMode", typeof(MaximizeMode), false);
            MissingItemPolicyType = new UIXEnumSchema(148, "MissingItemPolicy", typeof(MissingItemPolicy), false);
            MouseTargetType = new UIXEnumSchema(149, "MouseTarget", typeof(MouseTarget), false);
            NavigationPoliciesType = new UIXEnumSchema(151, "NavigationPolicies", typeof(NavigationPolicies), true);
            OrientationType = new UIXEnumSchema(154, "Orientation", typeof(Orientation), false);
            RelativeEdgeType = new UIXEnumSchema(170, "RelativeEdge", typeof(RelativeEdge), false);
            RepeatPolicyType = new UIXEnumSchema(172, "RepeatPolicy", typeof(RepeatPolicy), false);
            SharedSizePolicyType = new UIXEnumSchema(191, "SharedSizePolicy", typeof(SharedSizePolicy), true);
            ShortcutHandlerCommandType = new UIXEnumSchema(193, "ShortcutHandlerCommand", typeof(ShortcutHandlerCommand), false);
            SizingPolicyType = new UIXEnumSchema(199, "SizingPolicy", typeof(SizingPolicy), false);
            SnapshotPolicyType = new UIXEnumSchema(200, "SnapshotPolicy", typeof(SnapshotPolicy), false);
            StackPriorityType = new UIXEnumSchema(206, "StackPriority", typeof(StackPriority), false);
            StretchingPolicyType = new UIXEnumSchema(207, "StretchingPolicy", typeof(StretchingPolicy), false);
            StripAlignmentType = new UIXEnumSchema(209, "StripAlignment", typeof(StripAlignment), false);
            SystemSoundEventType = new UIXEnumSchema(211, "SystemSoundEvent", typeof(SystemSoundEvent), false);
            TextBoundsType = new UIXEnumSchema(213, "TextBounds", typeof(TextBounds), true);
            TextSharpnessType = new UIXEnumSchema(219, "TextSharpness", typeof(TextSharpness), false);
            TransformAttributeType = new UIXEnumSchema(223, "TransformAttribute", typeof(TransformAttribute), false);
            WindowStateType = new UIXEnumSchema(242, "WindowState", typeof(Microsoft.Iris.WindowState), false);
            AccessibleSchema.Pass1Initialize();
            AliasSchema.Pass1Initialize();
            AlphaKeyframeSchema.Pass1Initialize();
            AnchorEdgeSchema.Pass1Initialize();
            AnchorLayoutSchema.Pass1Initialize();
            AnchorLayoutInputSchema.Pass1Initialize();
            AnimationSchema.Pass1Initialize();
            AnimationHandleSchema.Pass1Initialize();
            BlendSchema.Pass1Initialize();
            BlurSchema.Pass1Initialize();
            BooleanSchema.Pass1Initialize();
            BooleanChoiceSchema.Pass1Initialize();
            BrightnessSchema.Pass1Initialize();
            BrightnessInstanceSchema.Pass1Initialize();
            ByteSchema.Pass1Initialize();
            ByteRangedValueSchema.Pass1Initialize();
            CameraSchema.Pass1Initialize();
            CameraAtKeyframeSchema.Pass1Initialize();
            CameraEyeKeyframeSchema.Pass1Initialize();
            CameraUpKeyframeSchema.Pass1Initialize();
            CameraZnKeyframeSchema.Pass1Initialize();
            CaretInfoSchema.Pass1Initialize();
            CharSchema.Pass1Initialize();
            ChoiceSchema.Pass1Initialize();
            ClassSchema.Pass1Initialize();
            ClassStateSchema.Pass1Initialize();
            ClickHandlerSchema.Pass1Initialize();
            ClipSchema.Pass1Initialize();
            ColorSchema.Pass1Initialize();
            ColorElementSchema.Pass1Initialize();
            ColorElementInstanceSchema.Pass1Initialize();
            CommandSchema.Pass1Initialize();
            ContrastSchema.Pass1Initialize();
            ContrastInstanceSchema.Pass1Initialize();
            DataMappingSchema.Pass1Initialize();
            DataQuerySchema.Pass1Initialize();
            DataTypeSchema.Pass1Initialize();
            DebugSchema.Pass1Initialize();
            DebugOutlinesSchema.Pass1Initialize();
            DefaultLayoutSchema.Pass1Initialize();
            DesaturateSchema.Pass1Initialize();
            DesaturateInstanceSchema.Pass1Initialize();
            DestinationElementSchema.Pass1Initialize();
            DestinationElementInstanceSchema.Pass1Initialize();
            DictionarySchema.Pass1Initialize();
            DockLayoutSchema.Pass1Initialize();
            DockLayoutInputSchema.Pass1Initialize();
            DoubleSchema.Pass1Initialize();
            DragHandlerSchema.Pass1Initialize();
            DragSourceHandlerSchema.Pass1Initialize();
            DropTargetHandlerSchema.Pass1Initialize();
            EdgeDetectionSchema.Pass1Initialize();
            EdgeDetectionInstanceSchema.Pass1Initialize();
            EditableTextDataSchema.Pass1Initialize();
            EffectSchema.Pass1Initialize();
            EffectAnimationSchema.Pass1Initialize();
            EffectColorAnimationSchema.Pass1Initialize();
            EffectColorKeyframeSchema.Pass1Initialize();
            EffectElementSchema.Pass1Initialize();
            EffectElementInstanceSchema.Pass1Initialize();
            EffectFloatAnimationSchema.Pass1Initialize();
            EffectFloatKeyframeSchema.Pass1Initialize();
            EffectInputSchema.Pass1Initialize();
            EffectInstanceSchema.Pass1Initialize();
            EffectLayerSchema.Pass1Initialize();
            EffectOperationSchema.Pass1Initialize();
            EffectVector3AnimationSchema.Pass1Initialize();
            EffectVector3KeyframeSchema.Pass1Initialize();
            EmbossSchema.Pass1Initialize();
            EmbossInstanceSchema.Pass1Initialize();
            EnumeratorSchema.Pass1Initialize();
            EnvironmentSchema.Pass1Initialize();
            EventContextSchema.Pass1Initialize();
            FlowLayoutSchema.Pass1Initialize();
            FocusHandlerSchema.Pass1Initialize();
            FontSchema.Pass1Initialize();
            FormLayoutInputSchema.Pass1Initialize();
            GraphicSchema.Pass1Initialize();
            GridLayoutSchema.Pass1Initialize();
            GroupSchema.Pass1Initialize();
            HostSchema.Pass1Initialize();
            HwndHostSchema.Pass1Initialize();
            IAnimationSchema.Pass1Initialize();
            ImageSchema.Pass1Initialize();
            ImageElementSchema.Pass1Initialize();
            ImageElementInstanceSchema.Pass1Initialize();
            IndexSchema.Pass1Initialize();
            InputHandlerSchema.Pass1Initialize();
            InsetSchema.Pass1Initialize();
            Int32Schema.Pass1Initialize();
            Int64Schema.Pass1Initialize();
            IntRangedValueSchema.Pass1Initialize();
            InterpolateElementSchema.Pass1Initialize();
            InterpolateElementInstanceSchema.Pass1Initialize();
            InterpolationSchema.Pass1Initialize();
            InvAlphaSchema.Pass1Initialize();
            InvColorSchema.Pass1Initialize();
            InvertSchema.Pass1Initialize();
            ItemAlignmentSchema.Pass1Initialize();
            KeyHandlerSchema.Pass1Initialize();
            KeyframeSchema.Pass1Initialize();
            LayoutSchema.Pass1Initialize();
            LayoutInputSchema.Pass1Initialize();
            LayoutOutputSchema.Pass1Initialize();
            LightShaftSchema.Pass1Initialize();
            LightShaftInstanceSchema.Pass1Initialize();
            ListSchema.Pass1Initialize();
            MajorMinorSchema.Pass1Initialize();
            MappingSchema.Pass1Initialize();
            MarkupSchema.Pass1Initialize();
            MarkupDataQueryInstanceSchema.Pass1Initialize();
            MarkupDataTypeInstanceSchema.Pass1Initialize();
            MarkupErrorSchema.Pass1Initialize();
            MathSchema.Pass1Initialize();
            MergeAnimationSchema.Pass1Initialize();
            MouseWheelHandlerSchema.Pass1Initialize();
            NullSchema.Pass1Initialize();
            ObjectSchema.Pass1Initialize();
            OrientationKeyframeSchema.Pass1Initialize();
            PanelSchema.Pass1Initialize();
            PlacementModeSchema.Pass1Initialize();
            PointSchema.Pass1Initialize();
            PointLight2DSchema.Pass1Initialize();
            PointLight2DInstanceSchema.Pass1Initialize();
            PopupLayoutSchema.Pass1Initialize();
            PopupLayoutInputSchema.Pass1Initialize();
            PopupPositionSchema.Pass1Initialize();
            PositionKeyframeSchema.Pass1Initialize();
            PositionXKeyframeSchema.Pass1Initialize();
            PositionYKeyframeSchema.Pass1Initialize();
            RandomSchema.Pass1Initialize();
            RangedValueSchema.Pass1Initialize();
            RectangleSchema.Pass1Initialize();
            RelativeToSchema.Pass1Initialize();
            RepeaterSchema.Pass1Initialize();
            RotateKeyframeSchema.Pass1Initialize();
            RotateLayoutSchema.Pass1Initialize();
            RotationSchema.Pass1Initialize();
            SavedKeyFocusSchema.Pass1Initialize();
            ScaleKeyframeSchema.Pass1Initialize();
            ScaleLayoutSchema.Pass1Initialize();
            ScaleXKeyframeSchema.Pass1Initialize();
            ScaleYKeyframeSchema.Pass1Initialize();
            ScrollModelSchema.Pass1Initialize();
            ScrollModelBaseSchema.Pass1Initialize();
            ScrollerSchema.Pass1Initialize();
            ScrollingHandlerSchema.Pass1Initialize();
            SelectionManagerSchema.Pass1Initialize();
            SelectionRangeSchema.Pass1Initialize();
            SepiaSchema.Pass1Initialize();
            SepiaInstanceSchema.Pass1Initialize();
            SharedSizeSchema.Pass1Initialize();
            ShortcutHandlerSchema.Pass1Initialize();
            SingleSchema.Pass1Initialize();
            SizeSchema.Pass1Initialize();
            SizeKeyframeSchema.Pass1Initialize();
            SizeXKeyframeSchema.Pass1Initialize();
            SizeYKeyframeSchema.Pass1Initialize();
            SoundSchema.Pass1Initialize();
            SpotLight2DSchema.Pass1Initialize();
            SpotLight2DInstanceSchema.Pass1Initialize();
            StackLayoutSchema.Pass1Initialize();
            StackLayoutInputSchema.Pass1Initialize();
            StringSchema.Pass1Initialize();
            SwitchAnimationSchema.Pass1Initialize();
            TextSchema.Pass1Initialize();
            TextEditingHandlerSchema.Pass1Initialize();
            TextFragmentSchema.Pass1Initialize();
            TextRunDataSchema.Pass1Initialize();
            TextRunRendererSchema.Pass1Initialize();
            TextScrollModelSchema.Pass1Initialize();
            TextStyleSchema.Pass1Initialize();
            TimerSchema.Pass1Initialize();
            TransformAnimationSchema.Pass1Initialize();
            TransformByAttributeAnimationSchema.Pass1Initialize();
            TypeSchemaDefinition.Pass1Initialize();
            TypeConstraintSchema.Pass1Initialize();
            TypeSelectorSchema.Pass1Initialize();
            TypingHandlerSchema.Pass1Initialize();
            UISchema.Pass1Initialize();
            UIStateSchema.Pass1Initialize();
            ValueRangeSchema.Pass1Initialize();
            ValueTransformerSchema.Pass1Initialize();
            Vector2Schema.Pass1Initialize();
            Vector3Schema.Pass1Initialize();
            VideoSchema.Pass1Initialize();
            VideoElementSchema.Pass1Initialize();
            VideoElementInstanceSchema.Pass1Initialize();
            VideoStreamSchema.Pass1Initialize();
            ViewItemSchema.Pass1Initialize();
            VoidSchema.Pass1Initialize();
            WindowSchema.Pass1Initialize();
            AccessibleSchema.Pass2Initialize();
            AliasSchema.Pass2Initialize();
            AlphaKeyframeSchema.Pass2Initialize();
            AnchorEdgeSchema.Pass2Initialize();
            AnchorLayoutSchema.Pass2Initialize();
            AnchorLayoutInputSchema.Pass2Initialize();
            AnimationSchema.Pass2Initialize();
            AnimationHandleSchema.Pass2Initialize();
            BlendSchema.Pass2Initialize();
            BlurSchema.Pass2Initialize();
            BooleanSchema.Pass2Initialize();
            BooleanChoiceSchema.Pass2Initialize();
            BrightnessSchema.Pass2Initialize();
            BrightnessInstanceSchema.Pass2Initialize();
            ByteSchema.Pass2Initialize();
            ByteRangedValueSchema.Pass2Initialize();
            CameraSchema.Pass2Initialize();
            CameraAtKeyframeSchema.Pass2Initialize();
            CameraEyeKeyframeSchema.Pass2Initialize();
            CameraUpKeyframeSchema.Pass2Initialize();
            CameraZnKeyframeSchema.Pass2Initialize();
            CaretInfoSchema.Pass2Initialize();
            CharSchema.Pass2Initialize();
            ChoiceSchema.Pass2Initialize();
            ClassSchema.Pass2Initialize();
            ClassStateSchema.Pass2Initialize();
            ClickHandlerSchema.Pass2Initialize();
            ClipSchema.Pass2Initialize();
            ColorSchema.Pass2Initialize();
            ColorElementSchema.Pass2Initialize();
            ColorElementInstanceSchema.Pass2Initialize();
            CommandSchema.Pass2Initialize();
            ContrastSchema.Pass2Initialize();
            ContrastInstanceSchema.Pass2Initialize();
            DataMappingSchema.Pass2Initialize();
            DataQuerySchema.Pass2Initialize();
            DataTypeSchema.Pass2Initialize();
            DebugSchema.Pass2Initialize();
            DebugOutlinesSchema.Pass2Initialize();
            DefaultLayoutSchema.Pass2Initialize();
            DesaturateSchema.Pass2Initialize();
            DesaturateInstanceSchema.Pass2Initialize();
            DestinationElementSchema.Pass2Initialize();
            DestinationElementInstanceSchema.Pass2Initialize();
            DictionarySchema.Pass2Initialize();
            DockLayoutSchema.Pass2Initialize();
            DockLayoutInputSchema.Pass2Initialize();
            DoubleSchema.Pass2Initialize();
            DragHandlerSchema.Pass2Initialize();
            DragSourceHandlerSchema.Pass2Initialize();
            DropTargetHandlerSchema.Pass2Initialize();
            EdgeDetectionSchema.Pass2Initialize();
            EdgeDetectionInstanceSchema.Pass2Initialize();
            EditableTextDataSchema.Pass2Initialize();
            EffectSchema.Pass2Initialize();
            EffectAnimationSchema.Pass2Initialize();
            EffectColorAnimationSchema.Pass2Initialize();
            EffectColorKeyframeSchema.Pass2Initialize();
            EffectElementSchema.Pass2Initialize();
            EffectElementInstanceSchema.Pass2Initialize();
            EffectFloatAnimationSchema.Pass2Initialize();
            EffectFloatKeyframeSchema.Pass2Initialize();
            EffectInputSchema.Pass2Initialize();
            EffectInstanceSchema.Pass2Initialize();
            EffectLayerSchema.Pass2Initialize();
            EffectOperationSchema.Pass2Initialize();
            EffectVector3AnimationSchema.Pass2Initialize();
            EffectVector3KeyframeSchema.Pass2Initialize();
            EmbossSchema.Pass2Initialize();
            EmbossInstanceSchema.Pass2Initialize();
            EnumeratorSchema.Pass2Initialize();
            EnvironmentSchema.Pass2Initialize();
            EventContextSchema.Pass2Initialize();
            FlowLayoutSchema.Pass2Initialize();
            FocusHandlerSchema.Pass2Initialize();
            FontSchema.Pass2Initialize();
            FormLayoutInputSchema.Pass2Initialize();
            GraphicSchema.Pass2Initialize();
            GridLayoutSchema.Pass2Initialize();
            GroupSchema.Pass2Initialize();
            HostSchema.Pass2Initialize();
            HwndHostSchema.Pass2Initialize();
            IAnimationSchema.Pass2Initialize();
            ImageSchema.Pass2Initialize();
            ImageElementSchema.Pass2Initialize();
            ImageElementInstanceSchema.Pass2Initialize();
            IndexSchema.Pass2Initialize();
            InputHandlerSchema.Pass2Initialize();
            InsetSchema.Pass2Initialize();
            Int32Schema.Pass2Initialize();
            Int64Schema.Pass2Initialize();
            IntRangedValueSchema.Pass2Initialize();
            InterpolateElementSchema.Pass2Initialize();
            InterpolateElementInstanceSchema.Pass2Initialize();
            InterpolationSchema.Pass2Initialize();
            InvAlphaSchema.Pass2Initialize();
            InvColorSchema.Pass2Initialize();
            InvertSchema.Pass2Initialize();
            ItemAlignmentSchema.Pass2Initialize();
            KeyHandlerSchema.Pass2Initialize();
            KeyframeSchema.Pass2Initialize();
            LayoutSchema.Pass2Initialize();
            LayoutInputSchema.Pass2Initialize();
            LayoutOutputSchema.Pass2Initialize();
            LightShaftSchema.Pass2Initialize();
            LightShaftInstanceSchema.Pass2Initialize();
            ListSchema.Pass2Initialize();
            MajorMinorSchema.Pass2Initialize();
            MappingSchema.Pass2Initialize();
            MarkupSchema.Pass2Initialize();
            MarkupDataQueryInstanceSchema.Pass2Initialize();
            MarkupDataTypeInstanceSchema.Pass2Initialize();
            MarkupErrorSchema.Pass2Initialize();
            MathSchema.Pass2Initialize();
            MergeAnimationSchema.Pass2Initialize();
            MouseWheelHandlerSchema.Pass2Initialize();
            NullSchema.Pass2Initialize();
            ObjectSchema.Pass2Initialize();
            OrientationKeyframeSchema.Pass2Initialize();
            PanelSchema.Pass2Initialize();
            PlacementModeSchema.Pass2Initialize();
            PointSchema.Pass2Initialize();
            PointLight2DSchema.Pass2Initialize();
            PointLight2DInstanceSchema.Pass2Initialize();
            PopupLayoutSchema.Pass2Initialize();
            PopupLayoutInputSchema.Pass2Initialize();
            PopupPositionSchema.Pass2Initialize();
            PositionKeyframeSchema.Pass2Initialize();
            PositionXKeyframeSchema.Pass2Initialize();
            PositionYKeyframeSchema.Pass2Initialize();
            RandomSchema.Pass2Initialize();
            RangedValueSchema.Pass2Initialize();
            RectangleSchema.Pass2Initialize();
            RelativeToSchema.Pass2Initialize();
            RepeaterSchema.Pass2Initialize();
            RotateKeyframeSchema.Pass2Initialize();
            RotateLayoutSchema.Pass2Initialize();
            RotationSchema.Pass2Initialize();
            SavedKeyFocusSchema.Pass2Initialize();
            ScaleKeyframeSchema.Pass2Initialize();
            ScaleLayoutSchema.Pass2Initialize();
            ScaleXKeyframeSchema.Pass2Initialize();
            ScaleYKeyframeSchema.Pass2Initialize();
            ScrollModelSchema.Pass2Initialize();
            ScrollModelBaseSchema.Pass2Initialize();
            ScrollerSchema.Pass2Initialize();
            ScrollingHandlerSchema.Pass2Initialize();
            SelectionManagerSchema.Pass2Initialize();
            SelectionRangeSchema.Pass2Initialize();
            SepiaSchema.Pass2Initialize();
            SepiaInstanceSchema.Pass2Initialize();
            SharedSizeSchema.Pass2Initialize();
            ShortcutHandlerSchema.Pass2Initialize();
            SingleSchema.Pass2Initialize();
            SizeSchema.Pass2Initialize();
            SizeKeyframeSchema.Pass2Initialize();
            SizeXKeyframeSchema.Pass2Initialize();
            SizeYKeyframeSchema.Pass2Initialize();
            SoundSchema.Pass2Initialize();
            SpotLight2DSchema.Pass2Initialize();
            SpotLight2DInstanceSchema.Pass2Initialize();
            StackLayoutSchema.Pass2Initialize();
            StackLayoutInputSchema.Pass2Initialize();
            StringSchema.Pass2Initialize();
            SwitchAnimationSchema.Pass2Initialize();
            TextSchema.Pass2Initialize();
            TextEditingHandlerSchema.Pass2Initialize();
            TextFragmentSchema.Pass2Initialize();
            TextRunDataSchema.Pass2Initialize();
            TextRunRendererSchema.Pass2Initialize();
            TextScrollModelSchema.Pass2Initialize();
            TextStyleSchema.Pass2Initialize();
            TimerSchema.Pass2Initialize();
            TransformAnimationSchema.Pass2Initialize();
            TransformByAttributeAnimationSchema.Pass2Initialize();
            TypeSchemaDefinition.Pass2Initialize();
            TypeConstraintSchema.Pass2Initialize();
            TypeSelectorSchema.Pass2Initialize();
            TypingHandlerSchema.Pass2Initialize();
            UISchema.Pass2Initialize();
            UIStateSchema.Pass2Initialize();
            ValueRangeSchema.Pass2Initialize();
            ValueTransformerSchema.Pass2Initialize();
            Vector2Schema.Pass2Initialize();
            Vector3Schema.Pass2Initialize();
            VideoSchema.Pass2Initialize();
            VideoElementSchema.Pass2Initialize();
            VideoElementInstanceSchema.Pass2Initialize();
            VideoStreamSchema.Pass2Initialize();
            ViewItemSchema.Pass2Initialize();
            VoidSchema.Pass2Initialize();
            WindowSchema.Pass2Initialize();
        }
    }
}
