<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>Library</OutputType>
        <AssemblyName>UIXsup</AssemblyName>
        <RootNamespace>Microsoft.Iris.Support</RootNamespace>
        <GenerateAssemblyInfo>true</GenerateAssemblyInfo>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    </PropertyGroup>
</Project>